# At every pull request, this workflow will install Poetry, project dependencies, lint and run tests.
# Github provides a complete guide on using python with Github Action so for 
# more information refer to:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check code on pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: dschep/install-poetry-action@v1.3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install project dependencies
      run: |
        poetry install

    - name: Lint with black
      run: |
        poetry run black .

    - name: Test with pytest
      run: |
        poetry run pytest
